use_eeg: False

Training1_trials_col_col: 0
Training1_trials_col1_col2: 0
Training1_trials_neu_neu: 0
Training1_trials_neu1_neu2: 0
Training1_trials_neutral: 10

Training2_trials_col_col: 6
Training2_trials_col1_col2: 6
Training2_trials_neu_neu: 6
Training2_trials_neu1_neu2: 6
Training2_trials_neutral: 0

Training_Resp_time: 4
Training_Wait_time: 1

Number_of_blocks: 1
Experiment_trials_col_col: 120
Experiment_trials_col1_col2: 120
Experiment_trials_neu_neu: 120
Experiment_trials_neu1_neu2: 120
Experiment_trials_neutral: 0

Experiment_Resp_time: 3
Experiment_Wait_time: 1

Jitter: 1

Fix_time: 1
Feedb: True
Feedb_time: 1

words_dist: 56
